; =============================================================================
; Sentinel Power Monitor
; Created By: Mr. Sunil Kumar S.
; LinkedIn:   https://www.linkedin.com/in/sunilkumarsekar/
; Year:       2026
; =============================================================================

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600
; upload_port   = COM5 ; Uncomment and modify if auto-detection fails

build_flags =
    -std=c++17
    -Iinclude
    -Ilib/LoggerService
    -Ilib/StorageService
    -Ilib/SystemService
    -Ilib/SchedulerService
    -Ilib/WiFiService
    -Ilib/NetworkService
    -Ilib/TimeService
    -Ilib/ProvisioningService
    -Ilib/JsonService
    -Ilib/TelegramService
    -Ilib/KeyboardService
    -Ilib/PowerMonitorService
    -Ilib/StatusService
    -Ilib/NotificationService

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0

lib_extra_dirs =
    lib
